config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "users#index"
  get "users/consult", to: "users#consult", as: :get
  resources :users, except: :foo
  get "u/foo", to: "users#foo"
  resources :logs, only: [:index, :create]
  get "logs/query", to: "logs#query"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/log 2.rb
class Log < ApplicationRecord
		enum opType: { crear: 0, modif: 1, elim: 2 }
end

app/models/log.rb
class Log < ApplicationRecord
	validates :docType, :docNum, :date, :opType, presence: true
	validates :docType, uniqueness: { scope: :docNum }
	validates :docNum, length: { maximum: 10 }
	validates :docNum, numericality: true

	enum docType: { cedula: 0, identidad: 1 }
	enum opType: { crear: 0, modif: 1, elim: 2 }

end

app/models/user.rb
class User < ApplicationRecord
	validates :docType, :docNum, :firstName, :secondName,
			:lastName, :dateBirth, :gender, :email,
			:phoneNumber, presence: true
  	validates :docType, uniqueness: { scope: :docNum }
	validates :email, uniqueness: true
	validates :docNum, :phoneNumber, length: { maximum: 10 }
	validates :docNum, :phoneNumber, numericality: true
	validates :firstName, :secondName, length: { maximum: 30}
	validates :lastName, length: { maximum: 60}
	validates :firstName, :secondName, format: { with: /\A[a-zA-Z]+\z/,
		message: "only allows letters" }
	validates :lastName, format: { with: /\A[a-zA-Z]+(\s[a-zA-Z]+)?\z/,
		message: "only allows letters" }
	validates :email, format: URI::MailTo::EMAIL_REGEXP
	#add photos max 2 mb
	
	enum docType: { cedula: 0, identidad: 1 }
	enum gender: { masculino: 0, femenino: 1, noBinario: 2, noResponde: 3 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  protect_from_forgery with: :null_session
end

app/controllers/logs_controller 2.rb
class LogsController < ApplicationController
	def show
		
	end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController

	def index
		whichLogs = params[:g]
		if whichLogs
			@logs = Log.where(id: whichLogs.pluck(:id))
		else
			@logs = Log.all
		end
	end

	def query
		conn = Faraday.new(url: ':3002')
		response = conn.post('/logs') do |req|
		  req.headers['Content-Type'] = 'application/json'
		  req.body = log_params
		end
		if response.status == 200
			@logs = []
			JSON.parse(response.body).each do |log|
				@logs.append(log)
			end
			redirect_to controller: :logs, action: :index, g: @logs
		end
	end

	protected

	def log_params
		params.permit(:docType, :docNum, :created_at).to_json
	end

	def set_logs
		#@logs = Log.where(id: @logs.)
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def consult
	end

	def new
		@user = User.new
	end

	def create
		req_params = {}
		9.times { |i| req_params[user_params.keys[i]] = user_params.values[i] }
		conn = Faraday.new(url: ':3001')
		
		response = conn.post('/users') do |req|
  			req.headers['Content-Type'] = 'application/json'
  			req.body = user_params.to_json
		end
		if response.status == 200
			@user = User.find(JSON.parse(response.body)["id"])

			redirect_to controller: :users, action: :show, id:@user.id

		else
			render "new"
		end
	end

	def foo
		response = Faraday.get(':3001/users/'.concat(
								params[:docType].to_s,"/", params[:docNum].to_s))
		if response.status == 200
			@user = User.find(response.body.to_i)
			redirect_to controller: :users, action: :show, id:@user.id
		else
			redirect_to controller: :users, action: :consult
		end
	end

	def show
		set_user
	end

	def edit
		set_user
	end

	def update
		conn = Faraday.new(url: ':3001')
		response = conn.patch('users/'.concat(params[:id].to_s)) do |req|
		  	req.headers['Content-Type'] = 'application/json'
		  	req.body = user_params.to_json
		end

		if response.status == 200
			@user = User.find(params[:id])
			redirect_to controller: :users, action: :show, id:@user.id
		else
			render status: 422
		end
	end

	def destroy
		@users = User.all
		conn = Faraday.new(url: ':3001')
		response = conn.delete('/users/'.concat(params[:id].to_s))
		if response.status == 200
			redirect_to controller: :users, action: :index
		else
			redirect_to controller: :users, action: :index
		end
	end

	private

	def user_params
		params.require(:user).permit(:docType,
				:docNum, :firstName, :secondName, :lastName,
				:dateBirth, :gender, :email, :phoneNumber)
	end

	def set_user
		@user = User.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logs_helper 2.rb
module LogsHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 

  </head>
  <style>
    body {
        font-family: 'Arial', sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4;
    }

    nav {
        background-color: #3498db;
        padding: 10px 0;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    }

    ul {
        list-style: none;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
    }

    li {
        margin: 0 15px;
    }

    a {
        text-decoration: none;
        color: #ffffff;
        font-size: 16px;
        font-weight: bold;
        transition: color 0.3s ease;
    }

    a:hover {
        color: #ecf0f1;
    }
</style>
  <body>
  <nav>
      <ul>
      <li><%= link_to "Nuevo", new_user_path %></li>
      <li><%= link_to "Consultar", users_consult_path %></li>
      <li><%= link_to "Log", logs_index_path %></li>
      <li><%= link_to "Index", users_path %></li>
      </ul>
    </nav>
    <%= yield %>
    
  </body>
</html>

app/views/logs/consultar.html.erb
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
    }
    div {
        display: flex;
        justify-content: space-between;
        margin: 20px;
        width: 100%;
    }

    h1 {
        margin-bottom: 20px;
    }

    form {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        width: 300px;
        margin: 20px;
    }

    label {
        display: block;
        font-size: 14px;
        margin-bottom: 5px;
    }

    select,
    input,
    date_field {
        width: 100%;
        padding: 10px;
        font-size: 14px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        margin-bottom: 10px;
    }

    input[type="submit"] {
        background-color: #3498db;
        color: #ffffff;
        border: none;
        padding: 10px 15px;
        font-size: 16px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    input[type="submit"]:hover {
        background-color: #2980b9;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
        overflow: hidden;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        background-color: #ffffff;
    }

    th, td {
        padding: 15px;
        text-align: left;
        border-bottom: 1px solid #dddddd;
    }

    th {
        background-color: #3498db;
        color: #ffffff;
    }

    tbody tr:hover {
        background-color: #f5f5f5;
    }
</style>
<table>
    <thead>
        <tr>
            <th>Tipo de Documento</th>
            <th>N. Documento</th>
            <th>Fecha </th>
            <th>Proceso</th>

            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @logs.each do |log| %>
            <tr>
                <td></td>
                <td><%= log.docType %></td>
                <td><%= log.docNum %></td>
                <td><%= log.date %></td>
                <td><%= log.opType %></td>

            </tr>
        <% end %>
    </tbody>
</table>

app/views/logs/index.html.erb
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
    }
    div {
        display: flex;
        justify-content: space-between;
        margin: 20px;
        width: 100%;
    }

    h1 {
        margin-bottom: 20px;
    }

    form {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        width: 300px;
        margin: 20px;
    }

    label {
        display: block;
        font-size: 14px;
        margin-bottom: 5px;
    }

    select,
    input,
    date_field {
        width: 100%;
        padding: 10px;
        font-size: 14px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        margin-bottom: 10px;
    }

    input[type="submit"] {
        background-color: #3498db;
        color: #ffffff;
        border: none;
        padding: 10px 15px;
        font-size: 16px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    input[type="submit"]:hover {
        background-color: #2980b9;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
        overflow: hidden;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        background-color: #ffffff;
    }

    th, td {
        padding: 15px;
        text-align: left;
        border-bottom: 1px solid #dddddd;
    }

    th {
        background-color: #3498db;
        color: #ffffff;
    }

    tbody tr:hover {
        background-color: #f5f5f5;
    }
</style>

<div>
    <div>
        <h1>Listado de logueos</h1>
    </div>
    <div>     
        <form action = "logs/query">           
            <br>
            <label for="docType">Tipo de Documento</label>
            <br>
            <select id="docType" name="docType">
            <option value=0>Cedula</option>
            <option value=1>Tarjeta Identidad</option>
            </select>
            <br>
            <label for="docNum">Número de Documento</label>
            <br>
            <input type="number" name="docNum" max=9999999999>
            <br>
            <label for="date">Fecha</label>
            <br>
            <%= date_field :date, id: 'created_at' %>
            <br>
            <input type="submit"/>
        </form>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Tipo de Documento</th>
            <th>N. Documento</th>
            <th>Fecha </th>
            <th>Proceso</th>

            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @logs.each do |log| %>
            <tr>
                <td></td>
                <td><%= log.docType %></td>
                <td><%= log.docNum %></td>
                <td><%= log.created_at %></td>
                <td><%= log.opType %></td>

            </tr>
        <% end %>
    </tbody>
</table>

app/views/logs/query.html.erb
<div>
    <div>
        <h1>Listado de logueos</h1>
    </div>
    <div>     
        <form action = "logs/query" method="GET" >           
            <br>
            <label for="docType">Tipo de Documento</label>
            <br>
            <select id="docType" name="docType", required>
            <option value=0>Cedula</option>
            <option value=1>Tarjeta Identidad</option>
            </select>
            <br>
            <label for="docNum">Número de Documento</label>
            <br>
            <input type="number" name="docNum" required max=9999999999>
            <br>
            <label for="date">Fecha</label>
            <br>
            <%= date_field :date, id: 'created_at' %>
            <br>
            <input type="submit"/>
        </form>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Tipo de Documento</th>
            <th>N. Documento</th>
            <th>Fecha </th>
            <th>Proceso</th>

            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @logs.each do |log| %>
            <tr>
                <td></td>
                <td><%= log.docType %></td>
                <td><%= log.docNum %></td>
                <td><%= log.created_at %></td>
                <td><%= log.opType %></td>

            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/consult.html.erb
<!-- En consultar.html.erb -->
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    form {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        width: 400px;
        margin: auto;
        justify-content: center;
        align-items: center;
    }

    label {
        display: block;
        font-size: 14px;
        margin-bottom: 5px;
    }

    select,
    input {
        width: 100%;
        padding: 10px;
        font-size: 14px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
        margin-bottom: 10px;
    }

    input[type="submit"] {
        background-color: #3498db;
        color: #ffffff;
        border: none;
        padding: 10px 15px;
        font-size: 16px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    input[type="submit"]:hover {
        background-color: #2980b9;
    }
</style>
<form action = "/u/foo" >
  <br>
  <label for="docType">Tipo de Documento</label>
  <br>
  <select id="docType" name="docType", required>
    <option value=0>Cedula</option>
    <option value=1>Tarjeta Identidad</option>
  </select>
  <br>
  <label for="docNum">Numero de Documento</label>
  <br>
  <input type="number" name="docNum" required max=9999999999>
  <br>
  <br>
  <input type="submit"/>
</form>

app/views/users/edit.html 2.erb
<%# user edit form %>

app/views/users/edit.html.erb
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
 
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    form {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        width: 400px;
        margin: auto;
    }

    div {
        margin-bottom: 5px;
    }

    label {
        display: block;
        font-size: 14px;
        margin-bottom: 5px;
    }

    select,
    input,
    textarea {
        width: 100%;
        padding: 10px;
        font-size: 14px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    select {
        height: 35px; /* Ajusta la altura según tus preferencias */
    }

    /* Personaliza el estilo del botón según tus preferencias */
    input[type="submit"] {
        background-color: #3498db;
        color: #ffffff;
        border: none;
        padding: 10px 15px;
        font-size: 16px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    input[type="submit"]:hover {
        background-color: #2980b9;
    }
</style>
<%= form_for @user, url: user_path, method: :patch do |f| %>

    <div>
        <%= f.label :'Tipo de documento',id: 'docType' %>
        <%= f.select :docType, User.docTypes.keys.map{ |key| [key.humanize, key] },value: @user.docType %>
    </div>
    <div>
        <%= f.label :'Número de Documento',id: 'docNum' %>
        <%= f.number_field :docNum, max: 9999999999,required: true,value: @user.docNum%>
    </div>
    <div>
        <%= f.label :Nombre ,id: 'firstName' %>
        <%= f.text_field :firstName ,required: true,maxlength: 30,value: @user.firstName%>
    </div>
    <div>
        <%= f.label :'Segundo nombre',id: 'secondName' %>
        <%= f.text_field :secondName, maxlength: 30, value:@user.secondName%>
    </div>
    <div>
        <%= f.label :Apellidos ,id: 'lastName' %>
        <%= f.text_field :lastName ,required: true, maxlength: 60,value: @user.lastName%>
    </div>
    <div>
        <%= f.label :Género,id: 'gender' %>
        <%= f.select :gender, User.genders.keys.map{ |key| [key.humanize, key] } ,required: true, value:@user.gender%>
    </div>
    <div>
        <%= f.label :'Fecha de Nacimiento ' ,id: 'dateBirth'%>
        <%= f.date_field :dateBirth, id: 'dateBirth' ,required: true,value: @user.dateBirth%>
    </div>
    <div>
        <%= f.label :email ,id: 'id_email'%>
        <%= f.email_field :email, id: 'email', class: 'form-control' ,required: true,value: @user.email%>
    </div>
    <div>
        <%= f.label :Número ,id: 'phoneNumber' %>
        <%= f.number_field :phoneNumber ,required: true, max:9999999999,value: @user.phoneNumber%>
    </div>
    <div>
        <%= f.submit 'Modificar', class: 'btn btn-primary' %>
    </div>
    
<% end %>

app/views/users/index.html.erb
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
    }
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
        overflow: hidden;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        background-color: #ffffff;
    }

    th, td {
        padding: 15px;
        text-align: left;
        border-bottom: 1px solid #dddddd;
    }

    th {
        background-color: #3498db;
        color: #ffffff;
    }

    tbody tr:hover {
        background-color: #f5f5f5;
    }
    .container {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px;
        background-color: #ffffff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
        margin: 0;
    }

    .buttons-container {
        display: flex;
        gap: 10px;
    }

    .btn {
        flex: 1;
        padding: 15px;
        font-size: 16px;
        text-align: center;
        text-decoration: none;
        background-color: #3498db;
        color: #ffffff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    .btn:hover {
        background-color: #2980b9;
    }
</style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">


<div class="container">
    <div>
        <h1>Listado de usuarios</h1>
    </div>
    <div class="buttons-container">
        <%= button_to "Nuevo", "/users/new",method: :get,class: "btn btn-info" %>
        <%= button_to "Log", "/logs",method: :get, class: "btn btn-info" %>
        <%= button_to "Consultar", "/users/consult", method: :get ,class: "btn btn-info" %>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Foto</th>
            <th>Tipo de Documento</th>
            <th>N. Documento</th>
            <th>Primer Nombre</th>
            <th>Segundo Nombre</th>
            <th>Apellidos</th>
            <th>Fecha de Nacimiento</th>
            <th>Género</th>
            <th>Correo Electrónico</th>
            <th>Celular</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
                <td></td>
                <td><%= user.docType %></td>
                <td><%= user.docNum %></td>
                <td><%= user.firstName %></td>
                <td><%= user.secondName %></td>
                <td><%= user.lastName %></td>
                <td><%= user.dateBirth %></td>
                <td><%= user.gender %></td>
                <td><%= user.email %></td>
                <td><%= user.phoneNumber %></td>
                <td><%= link_to "Modificar",
                            edit_user_path(user),
                            class: "btn btn-danger btn-lg"  %></td>
                <td><%= button_to "delete", user_path(user), method: :delete,
                            class: "btn btn-danger btn-lg"  %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/users/new.html.erb
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
 
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    form {
        background-color: #ffffff;
        padding: 20px;
        border-radius: 10px;
        
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
        width: 400px;
        margin: auto;
    }

    div {
        margin-bottom: 5px;
    }

    label {
        display: block;
        font-size: 14px;
        margin-bottom: 5px;
    }

    select,
    input,
    textarea {
        width: 100%;
        padding: 10px;
        font-size: 14px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-sizing: border-box;
    }

    select {
        height: 35px; /* Ajusta la altura según tus preferencias */
    }

    /* Personaliza el estilo del botón según tus preferencias */
    input[type="submit"] {
        background-color: #3498db;
        color: #ffffff;
        border: none;
        padding: 10px 15px;
        font-size: 16px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }

    input[type="submit"]:hover {
        background-color: #2980b9;
    }
</style>

<%= form_for(User.new) do |f| %>
    <div>
        <%= f.label :docType %>
        <%= f.select :docType, User.docTypes.keys.map{ |key| [key.humanize, key] } %>

    </div>
    <div>
        <%= f.label :docNum %>
        <%= f.text_field :docNum %>
    </div>
    <div>
        <%= f.label :firstName %>
        <%= f.text_field :firstName %>
    </div>
    <div>
        <%= f.label :'Segundo nombre' %>
        <%= f.text_field :secondName %>
    </div>
    <div>
        <%= f.label :Apellidos %>
        <%= f.text_field :lastName %>
    </div>
    <div>
        <%= f.label :dateBirth %>
        <%= f.date_field :dateBirth, class: 'form-control' %>
    </div>
    <div>
        <%= f.label :gender %>
        <%= f.select :gender, User.genders.keys.map{ |key| [key.humanize, key] } %>
    </div>
    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>
    <div>
        <%= f.label :Número %>
        <%= f.text_field :phoneNumber %>
    </div>
    <div>
        <%= f.submit %>
    </div>
<% end %>

app/views/users/show.html.erb
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
    }

    div {
        background-color: #ffffff;
        padding: 20px;
        margin: 10px;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h3 {
        color: #3498db;
    }

    .btn {
        background-color: #3498db;
        color: #ffffff;
        padding: 10px 15px;
        font-size: 16px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
        text-decoration: none;
        margin-top: 10px;
        display: inline-block;
    }

    .btn:hover {
        background-color: #2980b9;
    }
</style>

<div>
    
</div>
<div>
    <h3>Tipo de documento</h3>
    <%= @user.docType %>
</div>
<div>
    <h3>Número de Documento</h3>
    <%= @user.docNum %>
</div>
<div>
    <h3>Primer Nombre</h3>
    <%= @user.firstName %>
</div>
<div>
    <h3>Segundo Nombre</h3>
    <%= @user.secondName %>
</div>
<div>
    </h3>Apellidos</h3>
    <%= @user.lastName %>
</div>
<div>
    <h3>Gender</h3>
    <%= @user.gender%>
</div>
<div>
    <h3>Fecha de Nacimiento</h3>
    <%= @user.dateBirth %>
</div>
<div>
    <h3>email</h3>
    <%= @user.email%>
</div>
<div>
    <h3>Numero de Celular</h3>
    <%= @user.phoneNumber%>
</div>

<%= link_to "Volver", users_path, class: "btn btn-primary" %>

<%= button_to "delete", user_path(@user), method: :delete,
                            class: "btn btn-danger btn-lg"  %>